/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module show_component_16 (
    input [5:0] alufnvalue,
    output reg [2:0] address
  );
  
  
  
  localparam ADD = 6'h00;
  
  localparam SUB = 6'h01;
  
  localparam MUL = 6'h02;
  
  localparam AND = 6'h18;
  
  localparam OR = 6'h1e;
  
  localparam XOR = 6'h16;
  
  localparam ALDR = 6'h1a;
  
  localparam SHL = 6'h20;
  
  localparam SHR = 6'h21;
  
  localparam SRA = 6'h23;
  
  localparam CMPEQADD = 6'h32;
  
  localparam CMPEQSUB = 6'h33;
  
  localparam CMPLTADD = 6'h34;
  
  localparam CMPLTSUB = 6'h35;
  
  localparam CMPLEADD = 6'h36;
  
  localparam CMPLESUB = 6'h37;
  
  always @* begin
    if ((alufnvalue == 6'h00) | (alufnvalue == 6'h01) | (alufnvalue == 6'h02)) begin
      address = 3'h0;
    end else begin
      if ((alufnvalue == 6'h18) | (alufnvalue == 6'h1e) | (alufnvalue == 6'h16) | (alufnvalue == 6'h1a)) begin
        address = 3'h1;
      end else begin
        if ((alufnvalue == 6'h20) | (alufnvalue == 6'h21) | (alufnvalue == 6'h23)) begin
          address = 3'h2;
        end else begin
          if ((alufnvalue == 6'h32) | (alufnvalue == 6'h34) | (alufnvalue == 6'h36) | (alufnvalue == 6'h33) | (alufnvalue == 6'h35) | (alufnvalue == 6'h37)) begin
            address = 3'h3;
          end else begin
            address = 3'h4;
          end
        end
      end
    end
  end
endmodule
